sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "stable"
  - "10"
  - "11"
  - "12"
before_install:
  - npm install svgexport -g
  - npm install codecov -g
script:
  - npm run test-cov
  - codecov
after_success:
  - npm run lint
